### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: .tmp/pipeline.config 

### ISSUE THREAD

**Issue by atomsmasher81** [bourdakos1/tfjs-object-detection-training#3]
after I ran this command
`python -m object_detection.model_main \ --pipeline_config_path=.tmp/pipeline.config \ --model_dir=.tmp/checkpoint`

I got an error

`Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\Documents\GitHub\tfjs-object-detection-training\object_detection\model_main.py", line 109, in <module>
    tf.app.run()
  File "C:\Users\User\PycharmProjects\my_projects\object-detection\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "C:\Users\User\Documents\GitHub\tfjs-object-detection-training\object_detection\model_main.py", line 71, in main
    FLAGS.sample_1_of_n_eval_on_train_examples))
  File "C:\Users\User\Documents\GitHub\tfjs-object-detection-training\object_detection\model_lib.py", line 566, in create_estimator_and_inputs
    config_override=config_override)
  File "C:\Users\User\Documents\GitHub\tfjs-object-detection-training\object_detection\utils\config_util.py", line 95, in get_configs_from_pipeline_file
    proto_str = f.read()
  File "C:\Users\User\PycharmProjects\my_projects\object-detection\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 125, in read
    self._preread_check()
  File "C:\Users\User\PycharmProjects\my_projects\object-detection\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "C:\Users\User\PycharmProjects\my_projects\object-detection\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: .tmp/pipeline.config : The system cannot find the file specified.
; No such file or directory`

can you help me out, please?

**Comment by bourdakos1** [comment]
did you run the `python -m bucket.download` script?

**Comment by atomsmasher81** [comment]
i noticed just now that `python -m bucket.download` is also rasing an error after saving all image files
`
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\Documents\GitHub\tfjs-object-detection-training\bucket\download.py", line 221, in <module>
    create_tf_record(train_output_path, train_shards, train_examples)
  File "C:\Users\User\Documents\GitHub\tfjs-object-detection-training\bucket\download.py", line 185, in create_tf_record
    xmins.append(annotation['x'])
KeyError: 'x'
`

**Comment by atomsmasher81** [comment]
nevermind
fixed it
